
perms:
  commands:
    staff: server.staff
    staffchat: server.staffchat
    stafflab: server.stafflab
    freeze: server.freeze

  watch:
    staffchat: server.receive.staffchat
    vanish: server.receive.vanish



inventory:
  freeze:
    id: 1
    material: ICE

    title: "&aFreeze!"
    lore:
      - "&fClick to freeze a player."
      - ""

gui:
  freeze:
    title: "&aOnline players:"
    player:
      material: ICE

      title: "&a%player%"
      lore:
        - "&fClick to freeze this player."
        - ""
