name: StaffLab
version: 1.1
main: me.bryangaming.stafflab.StaffLab
author: BryanGaming
api-version: 1.13

commands:
  stafflab:
    description: A stafflab command.
  staff:
    description: A staff command.
  staffchat:
    description: A staffchat command.
  freeze:
    description: A freeze command.
  vanish:
    description: A vanish command.
  invsee:
    description: A invsee command.
